### ISSUE TITLE
不支持下载版权保护的视频，请问有办法解决吗？

### ISSUE THREAD

**Issue by DreamChaser2023** [here200/CCTallk-Video-Download-Extension#2]

**Comment by here200** [comment]
我针对以下两种情况进行分析：

HTML5：浏览器
	如果开启了版权保护，那么在Web端是获取不了正确的视频链接的。
	也就是，在Web端，CCTalk是直接不让你观看，自然没法下载。

客户端：手机APP
我对安卓版本的CCTalk APP进行了抓包，在观看、下载过程中，它采用的是MP2T协议。这种协议有点类似M3U8。
只是我没有学过音视频开发，对里边的协议不了解，很难编写程序去下载。

开启版权保护也是分情况的。一种是你可以在APP中下载，另外一种是不允许你下载的。
	如果允许你下载，就直接使用它的APP下载就行。手机空间不够，可以使用电脑开个安卓模拟器也行（CCTalk也有电脑版本）

总结一下
	如果在HTML5中能获取视频链接，就能直接下载。
	如果开启了版权保护，
		如果它允许你下载，可以使用CCTalk App进行下载。
		如果不允许，我也没办法（主要是本人能力有限，不了解音视频开发中的各种协议）
