### ISSUE TITLE
打包成软件报错

### ISSUE THREAD

**Issue by L134139** [here200/CCTallk-Video-Download-Extension#4]
![8](https://github.com/here200/CCTalk-Video-Download-Extension/assets/51356527/349e65dc-1c6d-41ee-8160-b9c0784f7a6f)

**Comment by 33a3** [comment]
没有下载相应模块。如: jsonpath。

**Comment by 33a3** [comment]
需要下载的模块在 requirements.txt 里有说明

**Comment by L134139** [comment]
![9](https://github.com/here200/CCTalk-Video-Download-Extension/assets/51356527/580449db-4835-4a00-920d-a3be27677cb3)
这个是什么问题

**Comment by 33a3** [comment]
可能是cctalk的接口发生了变化。现在在外面，没时间更新项目。

**Comment by 33a3** [comment]
也可能是你把视频id写错了

**Comment by lawlorentz** [comment]
应该是接口变了

**Comment by 52beijixing** [comment]
> ![9](https://user-images.githubusercontent.com/51356527/253974677-580449db-4835-4a00-920d-a3be27677cb3.png)这个是什么问题

这个程序目前不支持主课程解析，你写的id是主课程id，对应的子课程id为1587649584526555。你试试这个id，就可以解析了
